export const COMPANY_NAMES = {
  'MSFT': 'Microsoft',
  'AAPL': 'Apple',
  'GOOGL': 'Google',
  'AMZN': 'Amazon',
  'TSLA': 'Tesla',
  'META': 'Meta',
  'NVDA': 'NVIDIA',
  'AMD': 'AMD',
  'INTC': 'Intel',
  'JPM': 'JPMorgan',
  'BAC': 'Bank of America',
  'WFC': 'Wells Fargo',
  'GS': 'Goldman Sachs',
  'MS': 'Morgan Stanley',
  'WMT': 'Walmart',
  'KO': 'Coca-Cola',
  'PEP': 'PepsiCo',
  'MCD': "McDonald's",
  'TM': 'Toyota',
  'F': 'Ford',
  'JNJ': 'Johnson & Johnson',
  'PFE': 'Pfizer',
  'ABBV': 'AbbVie',
  'MRK': 'Merck',
  'LLY': 'Eli Lilly',
  'XOM': 'Exxon Mobil',
  'CVX': 'Chevron',
  'NEE': 'NextEra Energy',
  'SO': 'Southern Company',
  'BA': 'Boeing',
  'CAT': 'Caterpillar',
  'HON': 'Honeywell',
  'MMM': '3M',
  'CSCO': 'Cisco',
  'ORCL': 'Oracle',
};

export function getCompanyName(ticker) {
  return COMPANY_NAMES[ticker?.toUpperCase()] || ticker;
}
